### ISSUE TITLE
Links that go nowhere cause the obf output to break. :( 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#126]
argument is 
Traceback (most recent call last):
  File "grab_text.py", line 543, in <module>
    write_to_obf(pageset.grids, dest)
  File "grab_text.py", line 481, in write_to_obf
    create_obf_manifest(boards_names_dic,image_names_dic, dest)
  File "grab_text.py", line 363, in create_obf_manifest
    root = boards_names_dic['toppage']
KeyError: 'toppage'
Josephs-Mini:openvoicefactory josephreddington$

**Comment by joereddington** [comment]
Spent some time on this today.  Turns out it revealed a few bits that weren't working very well.  

There's now a list of what needs to happen. 

- [ ] the other language versions should be checked manually to make sure they really do work.  
- [ ] add the brazil version to the test cases for regression (which will also let us run the localcreate command easily on the staging server. 
- [ ] regression tests need to include the obz files as well. 
- [ ] all ascii('ignores') should be made into ascii('replaces')

**Comment by joereddington** [comment]
Actually here's the plan. 

* Get the new file to be part of the tests. 
* Remove all of the encode/decode commands 
* Run the tests 
* Put in all the exception handling we need to properly understand this. 
* Put in the correct encode/decode commands.

**Comment by joereddington** [comment]
Dealt with in the June updates
