### ISSUE TITLE
2017-03-03 Export pagesets to OBF

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#40]
https://trello.com/c/ohUXlGUh/40-export-pagesets-to-obf

**Comment by joereddington** [comment]
###### 02/03/17 08:50: 


I got a very long way with this recently, but it's now long enought ago that I need to spend some time working out exactly where I got to.  


###### 02/03/17 08:52: 
I need to look at the GitX, and the previous log.  But where did I put it? 

###### 08:53: 
GitX tells me that the last commit was 828e8042ead2e092345bfad690a1fcd33a453779  and it was on the ovfoutput branch. Let's open that. 

###### 08:54: 
It was also on the 11th Feb, let's see what logs I have for that period. 

###### 08:55: 
My log file is at: 2017-02-12-obf.md  

###### 08:56: 
Some interesting snippets from the log file. 

* I've been doing this since last june!
* I wrote a very deliberate set of tests for this, we should find them. 
* I'd emailed brian with some files, we should grab those as well. 

###### 08:58: 
The turn test harnesses turn out to be in a separate github repo (which I could make public at some point). 

The email answer I got was : 

```
it looks like it's getting stuck when parsing myday.obf, because it references a path "boards/special::unfinnished.obf" that doesn't exist.

```

Which is a point I can look into.  

Now the code...

###### 09:05: 
I've run the localcreate command: 

    38938  02/03/17 09:04:04 ./localcreate.sh ../CommuniKate/ck20/CK20V2.pptx 5


and by going into the generated folder and then the obf folder I have found pageset.obz.  

###### 09:16: 
I'm having some small internet problems. Stand by.  

I've had a look at the code and realised that I'd commented out the lines that caused problems anyway.  I'm regenerating now.  

###### 09:19: 
###### 09:29: 
For the sake of the argument, I've switched to phoen internet. Sigh. 

###### 09:30: 
I've checked with the validator, and we are now getting errors around the special commands, pressuambly because there is a different way of doing special commands in OBF. 

There are two ways to move forward with this: 

* take out the special commands temporarily and just get the output working 
* workout what's going on with special commands. 

I think the code for the second option includes the code for the first, so let's do that for now. 

###### 09:34: 
I've added the code, regenerating.

**Comment by joereddington** [comment]
###### 10:18: 
It appears that I need to define the images in two places, once in the manifest, and once in the file. The file one is more complex. but we'll see. 

I've made some changes and I'm regenerating. 

###### 10:28: 
![screen shot 2017-03-02 at 10 32 19](https://cloud.githubusercontent.com/assets/4369547/23503427/ac41f70e-ff33-11e6-9123-8569a29f7fb4.png)

Ah "processing failed" That's new.  I've just run some files thought a JSON validator and it appears that there was something wrong with my JSON ( a comma rather than a colon), so I'm regenerating. 

###### 10:30: 
###### 10:40: 
Just stopped to think for a while there. Might be time to move on to something else. 

###### 10:41: 
But my OBF is now valid, so I'll take it, generating preview now. 


###### 10:44: 
Ah-ha! I have images: 
![screen shot 2017-03-02 at 10 43 55](https://cloud.githubusercontent.com/assets/4369547/23503850/2ef0465a-ff35-11e6-9823-7f7413c9a86e.png)

Time for a commit. 

###### 10:45: 
So, what to do now? I have to get images into the format and there are three things to do: 

* Make sure they are all in the manifest 
* Make sure they are all in the board ovf file 
* Make sure the image files are in the images directory

Of these, the last is the trickiest. At the moment I store them in the 'icon' directory I could: 

* Just change the location: obf becomes... data? and icons becomes data/images? 
* Double up - just have two folders. 

I think the first one is best, I want to be careful that it doesn't impact on the webapp though. I've checked the code and I believe that the image paths are stored in the json anyway, so can be moved easily. 

###### 10:53: 
I've changed the python, let's see what it looks like. Generating (and regenerating after changing some files in the template (which need to be made part of git...) 

###### 11:02: 
Deeply confused by this bug: 

```
CK20V2.pptx/data/boards/toppage.obf
Traceback (most recent call last):
  File "grab_text.py", line 490, in <module>
    write_to_obf(grids, dest)
  File "grab_text.py", line 416, in write_to_obf
    with open(dest+'/data/'+filename, 'w') as outfile:
IOError: [Errno 2] No such file or directory: 'CK20V2.pptx/data/boards/toppage.obf'
MacBook-Air:openvoicefactory josephreddington$ 
```

I'm opening it to write it, and the directory is there... 

###### 11:09: 
Hmm.  The images are going over nicely. But the boards are strange. When I changed it back, it stopped again, but on a different thing.  That's deeply odd.  

###### 11:10: 
I'm going to branch to do a MCVE

###### 11:15: 
Did some dramatic changes but don't know which one did it, so starting again. 

###### 11:22: 
Hmm. It appears to be something about running the thing twice. Which suggests it's go a lot to do with the file structure. 

###### 11:26: 
Yeah, runnning it twice makes the thing work. What am I missing? 

###### 11:27: 
Hang on - changing the script. Regenerating. 
###### 11:29: 
And we've solved that problem. Now where actually where we? 

Oh yes, We were changing the code so that *all* images would work. Let's get back to that. 

###### 11:33: 
I'm changing a lot of code and I feel like very little of it will work :( 

###### 11:35: 
I've just committed - here's what's next
I'm looking at the for loop at 410. The loop needs to populate image_names_dic by looping over all the icons in the board and putting them in.  

###### 11:38: 
Hang on. I think I did something...  Generating... fixing a typo... regenerating... fixing a typo... regenerating

###### 11:42: 
Definately very tired. Time to stop soon. But I want this to really work.   

###### 11:47: 
Fixing a typo... regenerating... fixing a typo... 

###### 11:52: 

Okay, let's have another look 

###### 11:55: 
Error! Processing failed... Let's look at the manifest. 

There is a problem in the manifest, but I'm struggling to see what it is... 


###### 12:15: 
Had a break.  Back now. 

###### 12:20: 
The bug seems to be around having to many curly brace around symbols.  I'm uploading a new version now.  

###### 12:23: 
That failed as well. Interesting Wonder what happened. Regenerating just incase I'd failed to save it.   

###### 12:31: 
Hmm. It's still there, but I'm certain it's out of the code... hmm... 

###### 12:36: 
Stranger and stranger. It's now valid JSON, but it still gets processing failed... hmm...

**Comment by joereddington** [comment]
###### 12:38: 
Okay, various errors in the validator - that's worth working on - mostly around the image paths not being found.  That will need a little bit of careful thinking about.  But time for lunch now.

**Comment by joereddington** [comment]
###### 13/03/17 08:48: 
Okay, let's have a look.  

###### 08:50: 
Here are the things I have to solve: 


* 	 Error: image.path "" not found in .obz package
*  image.path "data/images/S8X4Y4favoritefood.png" not found in .obz package

###### 08:55: 
Hmm, I've added back in a four loop that was clearly missing... 

###### 08:57: 
Okay, I'm trying to solve the second of the bullet points (I think I've done the first) - there is a problem that means that I'll have to change the web client if I'm uncareful... :s 

###### 09:04:
Getting nowhere, can't even work out what I'm missing. I know I've gotten futhur than this thought... I did a snapshot didn't I? 


###### 09:10: 
I'm starting to think I'm going to be reduced to just emailing obf about this one... 

![screen shot 2017-03-13 at 09 10 55](https://cloud.githubusercontent.com/assets/4369547/23848018/ff075546-07cc-11e7-8b6d-bf13b18ebdea.png)

It's definately the path, and the files are definately in the images directory...  


###### 09:13: 
Ah-ha! Looking back thought gitX did it - I've not added the images to the actual zip file. Hang on. 

###### 09:23: 
Making the change...

###### 09:31: 
Worked! 

###### 09:31: 
What's next? 

###### 09:32: 
Special commands are next, and that might need a Skype conversation with the OVF guys.

**Comment by joereddington** [comment]
###### 14/08/17 11:25: 

Here's what we should have for controls: 

```
clear:
{
"id": 1,
"label": "clear",
"action": ":clear"
}

backspace:
{
"id": 2,
"label": "clear",
"action": ":clear"
}

link-and-insert-text:
{
"id": 3,
"label": "I want some",
"load_board": {...}
"ext_coughdrop_add_to_vocalization": true
}
```
And I feel like the steps now are: 

- [ ] notice that clear and backspace are the same and email brain about that. 
- [x] wipe the current set of boards in cough drop
- [x] branch for commands. 
- [ ] open grab_text.py and see if anyhthing is bovious. 


###### 11:35: 
Okay, so the first thing to notice is that the current create_obf_object() is horrifically complex and should be refactored.   Unsure what the best way of doing that is. Unless we have a hash function. 

###### 11:37: 
This file gives an answer: http://osxdaily.com/2009/10/13/check-md5-hash-on-your-mac/  I can use the hash command. Let's check.

md5 aidCK20V2.pptx/data/pageset.obz 
MD5 (aidCK20V2.pptx/data/pageset.obz) = a8b508085c7fd4d349eba14fb0e86684
MacBook-Air:openvoicefactory josephreddington$ cp aidCK20V2.pptx/data/pageset.obz target.obz 
MacBook-Air:openvoicefactory josephreddington$ md5 target.obz 
MD5 (target.obz) = a8b508085c7fd4d349eba14fb0e86684
MacBook-Air:openvoicefactory josephreddington$  

###### 11:46: 
Hash keeps failing when it shouldn't.  There's NO way it's failing right now surely... 

###### 11:50: 
Wait... it was...  But that might be beause the code itself is failing - I created it after an image problem .

###### 11:53: 
Crap - the target is invalid as well.  Back a stage. 
###### 12:03: 
I've cahnged some paths and we're still broken. 

###### 12:16: 
I'm back after brief interruption. 
###### 12:24: 
Think we're working but I really need to commit - I did a bit of a daring refacting there and it might have failed. 

###### 12:26: 
Uploading a version. 

###### 12:32: 
Working again. Have commited. ([obfcommands 40147fc] fixed a bug). Haven't made much progress tho... 

 J



# Next actions 
* Check you haven't completely screwed up the web app
* start project to update the web app to OVF

**Comment by joereddington** [comment]
###### 16/08/17 10:33: 
I've created a new issue for updating the web app 

###### 10:34: 
I'm running local create to check that the web app works.  Taking a while. 


###### 10:36: 
It works fine. And the git is up to date. Let's try grap_text. 

###### 10:37: 
Oh yes, I was refacting in a big way. 

###### 10:40: 
I'm refactoring out some functions for now. We'll build them into the class later. 

###### 10:47: 
###### 10:57: 
I've done some work - I'm making my life easier my doing a long overdue 'removing classes to their own files 


# Next actions 
* Check branch.  
* Try the clear command (up until this point, grab_text has never had to know about any of the actual.. *commands*.

**Comment by joereddington** [comment]
###### 02/01/18 11:02 to 11:43:
I've come back to this after a while away and I come up to date.  It looks like I was in the middle of a big refactor last time, and I possibly was halfway though an error. That's less than ideal but I can work with it.  


Here's where I am.
* All (13/13) tests pass on the master branch
* There is an active developement branch called obfcommands, it's about a dosen commits futher on and four of its 14 tests are currently failing. 
* Looking at the pageset.obz files that are being generated - a major problem is that the 'button' part is Null.  That's one of the next things to fix.  

# Next actions
* Find the email you sent to Brian last - it will have some info in it.
* Compare the master and obfcommand branches properly.

**Comment by joereddington** [comment]
Done elsewhere.
